CREATE TABLE IF NOT EXISTS tales (
                                     id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     title VARCHAR(255) NOT NULL,
    content VARCHAR(5000),
    author VARCHAR(255),
    rating INT
    );